blueprint:
  name: Yet Another Motion Automation
  description: "# YAMA V11.1 (Optimized)\n\nTurn on lights or scenes when motion is
    detected optional with lumiance sensor. \nFour different scenes can be defined
    depending on time of day.\n\nCapabilitys:\n\n - Trigger on motion (in fact can
    be triggered by anything that switches between “on” and off\")\n - Wait time for
    turning off\n - Only run if entity is in desired state (optional)\n - Sun elevation
    check (optional)\n - 4 Scenes for different times of day (optional)\n - Ambient
    support with time frame (optional)\n - Default scene when motion stops (optional)\n
    - “no motion blocker” with user choosable state (optional)\n - As option one or
    more illumiance sensors can be used\n  - Scene.none removed and optimized for new
    Home Assistant features\n"
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      description: Motion Sensor or a group with Motion Sensors (But can be anything
        switching between "on" and "off")
      selector:
        entity:
          multiple: true
          reorder: false
    light_target:
      name: Light
      selector:
        target:
          entity:
          - domain:
            - light
    luminance_sensor:
      name: Illuminance sensor
      description: This sensor will be used to determine the illumination.
      default: []
      selector:
        entity:
          domain:
          - sensor
          device_class:
          - illuminance
          multiple: true
          reorder: false
    luminance_required:
      name: Required Lux Level
      description: Lux level below which the automation will run.
      default: 100
      selector:
        number:
          min: 0.0
          max: 10000.0
          unit_of_measurement: lx
          step: 1.0
          mode: slider
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
    automation_blocker:
      name: Automation Blocker (Optional)
      description: Only run if this boolean is in desired state (see next input)
      default: ''
      selector:
        entity:
          multiple: false
          reorder: false
    automation_blocker_boolean:
      name: Automation Blocker Chooser (Optional)
      description: Desired state of automation blocker, choose on for on and off for
        off
      default: false
      selector:
        boolean: {}
    no_motion_blocker:
      name: No Motion Blocker (Optional)
      description: No motion sequence is not run if this boolean is in desired state
        (see next input)
      default: ''
      selector:
        entity:
          multiple: false
          reorder: false
    no_motion_blocker_boolean:
      name: No Motion Chooser (Optional)
      description: Desired state of no motion blocker, choose on for on and off for
        off
      default: false
      selector:
        boolean: {}
    elevation_check:
      name: Sun elevation check (Optional)
      description: This is the angle between the sun and the horizon. Negative values
        mean the sun is BELOW the horizon.
      default: none
      selector:
        number:
          min: -90.0
          max: 90.0
          unit_of_measurement: degrees
          step: 1.0
          mode: slider
    scene_ambient:
      name: Ambient Scene (Optional)
      description: Scene for ambient state. Will be activated when no motion is detected.
      default: ''
      selector:
        entity:
          domain:
          - scene
          multiple: false
          reorder: false
    time_scene_ambient_start:
      name: Ambient time frame start (Optional)
      description: Time from which on ambient scene will be activated
      default: 00:00:00
      selector:
        time: {}
    time_scene_ambient_end:
      name: Ambient time frame end (Optional)
      description: Time from which on ambient scene will be not activated
      default: 00:00:00
      selector:
        time: {}
    scene_morning:
      name: Scene for the morning (Optional)
      default: ''
      selector:
        entity:
          domain:
          - scene
          multiple: false
          reorder: false
    time_scene_morning:
      name: Time for the morning scene (Optional)
      description: A time input which defines the time from which on the scene will
        be activated if motion is detected.
      default: 00:00:00
      selector:
        time: {}
    scene_day:
      name: Scene for the bright day (Optional)
      default: ''
      selector:
        entity:
          domain:
          - scene
          multiple: false
          reorder: false
    time_scene_day:
      name: Time for the day scene (Optional)
      description: A time input which defines the time from which on the scene will
        be activated if motion is detected.
      default: 00:00:00
      selector:
        time: {}
    scene_evening:
      name: Scene for the evening (Optional)
      default: ''
      selector:
        entity:
          domain:
          - scene
          multiple: false
          reorder: false
    time_scene_evening:
      name: Time for the evening scene (Optional)
      description: A time input which defines the time from which on the scene will
        be activated if motion is detected.
      default: 00:00:00
      selector:
        time: {}
    scene_night:
      name: Scene for the dark night (Optional)
      default: ''
      selector:
        entity:
          domain:
          - scene
          multiple: false
          reorder: false
    time_scene_night:
      name: Time for the night scene (Optional)
      description: A time input which defines the time from which on the scene will
        be activated if motion is detected.
      default: 00:00:00
      selector:
        time: {}
    scene_no_motion:
      name: Default scene for no motion (Optional)
      description: Set this Scene if you want to activate a scene if motion stops
      default: ''
      selector:
        entity:
          domain:
          - scene
          multiple: false
          reorder: false
  source_url: https://github.com/Stephan-4711/HomeAssistant_Blueprints/blob/main/advanced_custom_motion_sensor.yaml
mode: restart
max_exceeded: silent
variables:
  scene_ambient: !input scene_ambient
  scene_morning: !input scene_morning
  scene_day: !input scene_day
  scene_evening: !input scene_evening
  scene_night: !input scene_night
  automation_blocker: !input automation_blocker
  automation_blocker_boolean: !input automation_blocker_boolean
  no_motion_blocker: !input no_motion_blocker
  no_motion_blocker_boolean: !input no_motion_blocker_boolean
  elevation_check: !input elevation_check
  scene_no_motion: !input scene_no_motion
  motion_entity: !input motion_entity
  luminance_sensor: !input luminance_sensor
  luminance_required: !input luminance_required
trigger:
- platform: state
  entity_id: !input motion_entity
  from: 'off'
  to: 'on'
  id: motion_on
- platform: state
  entity_id: !input motion_entity
  from: 'on'
  to: 'off'
  for: !input no_motion_wait
  id: motion_off
condition:
- condition: or
  conditions:
  - '{{ automation_blocker is none or automation_blocker == "none" or automation_blocker
    == "" }}'
  - '{{ automation_blocker_boolean and states(automation_blocker) == "off" }}'
  - '{{ not automation_blocker_boolean and states(automation_blocker) == "on" }}'
  - condition: trigger
    id: motion_off
- condition: template
  value_template: '{{ trigger.id == ''motion_off'' or elevation_check is none or elevation_check
    == ''none'' or elevation_check == '''' or (state_attr(''sun.sun'', ''elevation'')
    <= elevation_check | float(90)) }}'
action:
- choose:
  - conditions:
    - condition: trigger
      id: motion_on
    - condition: or
      conditions:
      - '{{ luminance_sensor is none or luminance_sensor == "none" or luminance_sensor
        == [] or luminance_sensor == "" }}'
      - condition: numeric_state
        entity_id: !input luminance_sensor
        below: !input luminance_required
    sequence:
    - choose:
      - conditions:
        - '{{ scene_morning is defined and scene_morning != none and scene_morning
          != "none" and scene_morning != "" }}'
        - condition: time
          after: !input time_scene_morning
          before: !input time_scene_day
        sequence:
        - action: scene.turn_on
          target:
            entity_id: '{{ scene_morning }}'
      - conditions:
        - '{{ scene_day is defined and scene_day != none and scene_day != "none" and
          scene_day != "" }}'
        - condition: time
          after: !input time_scene_day
          before: !input time_scene_evening
        sequence:
        - action: scene.turn_on
          target:
            entity_id: '{{ scene_day }}'
      - conditions:
        - '{{ scene_evening is defined and scene_evening != none and scene_evening
          != "none" and scene_evening != "" }}'
        - condition: time
          after: !input time_scene_evening
          before: !input time_scene_night
        sequence:
        - action: scene.turn_on
          target:
            entity_id: '{{ scene_evening }}'
      - conditions:
        - '{{ scene_night is defined and scene_night != none and scene_night != "none"
          and scene_night != "" }}'
        - condition: time
          after: !input time_scene_night
          before: !input time_scene_morning
        sequence:
        - action: scene.turn_on
          target:
            entity_id: '{{ scene_night }}'
      default:
      - action: light.turn_on
        target: !input light_target
  - conditions:
    - condition: trigger
      id: motion_off
    - condition: or
      conditions:
      - '{{ no_motion_blocker is none or no_motion_blocker == "none" or no_motion_blocker
        == "" }}'
      - '{{ no_motion_blocker_boolean and states(no_motion_blocker) == "off" }}'
      - '{{ not no_motion_blocker_boolean and states(no_motion_blocker) == "on" }}'
    sequence:
    - choose:
      - conditions:
        - '{{ scene_ambient is defined and scene_ambient != none and scene_ambient
          != "none" and scene_ambient != "" }}'
        - condition: time
          after: !input time_scene_ambient_start
          before: !input time_scene_ambient_end
        sequence:
        - action: scene.turn_on
          target:
            entity_id: '{{ scene_ambient }}'
      - conditions:
        - '{{ scene_no_motion is defined and scene_no_motion != none and scene_no_motion
          != "none" and scene_no_motion != "" }}'
        sequence:
        - action: scene.turn_on
          target:
            entity_id: '{{ scene_no_motion }}'
      default:
      - action: light.turn_off
        target: !input light_target
